#!/usr/bin/env python3

from multiplexing.server.server import Server
from multiplexing.server.config import Config


def main():
    server = Server(Config(service_hostname="cloud.jace.website"))
    server.start()


if __name__ == '__main__':
    main()
