#!/usr/bin/env python3

from multiplexing.server.server import Server
from multiplexing.server.config import Config


def main():
    server = Server(Config())
    server.start()


if __name__ == '__main__':
    main()
